version: '3.1'
services:
  selenium-hub:
    image: selenium/hub
    ports:
      - 4444:4444
    networks:
      - instabot

  chrome:
    image: selenium/node-chrome
    links:
      - selenium-hub:hub
    environment:
      HUB_HOST: hub
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - instabot

  bot:
    build:
      context: .
      args:
        - PROJECT_DIR=/opt/instbot
    image: insta_bot
    container_name: ibot
    volumes:
      - .:/opt/instbot
    env_file:
      - etc/.env
    networks:
      - instabot
    restart: on-failure
    depends_on:
      - chrome
      - selenium-hub
      - amqp
    links:
      - selenium-hub:hub
      - chrome:chrome
      - amqp:amqp
    command:
      - "sh"
      - "-c"
      - "alembic upgrade head && celery worker -A tasks -B -l info --autoscale=2,1"

  amqp:
    container_name: bot_amqp
    image: rabbitmq:3.6.5-management
    ports:
      - 12672:15672
    networks:
      - instabot

networks:
  instabot:
    driver: bridge
